name: Github Action demo
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Print index file
        run: cat index.html 
