name: multiple shell command in single steps.
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: Hello step
       run: |
        echo "This is line one"
        echo "This is line two"
