name: Push and pull event
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Demo
      run: echo "Hello build"
  test:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: executing test cases
     run: test cases running....


